

= Learning Websocket

== Todo List

* [ ] WebSocket 发展历史及其现状
. RFC 6455 协议文档
* [ ] WebSocket 常见实现方案
. 基于原生 Java 实现
. 基于 Spring 实现
. 基于 SpringBoot 实现
. 基于 Netty 实现
. 前端集成 WebSocket
* [ ] WebSocket 服务的测试与运维（部署、监控及告警）
* [ ] WebSocket 服务的高可靠、高可用、高性能实践
* [ ] WebSocket 推送技术在企业信息化/数字化系统中的应用场景
* [ ] WebSocket 工业级实践方案


素材：
博客：

https://www.baeldung.com/java-enterprise-evolution[Java EE vs J2EE vs Jakarta EE]
https://blog.csdn.net/zl1zl2zl3/article/details/86030331[【译】Java EE vs J2EE vs Jakarta EE]

https://www.cnblogs.com/kiwifly/p/11729304.html[Spring boot 集成 websocket 的四种方式 ]


https://www.javainuse.com/spring/boot-websocket[使用SpringBoot构建一个Websocket应用]



https://blog.csdn.net/An1090239782/article/details/107173448[基于Netty的高性能WebSocket服务器实现方案-netty-websocket-spring-boot-starter]

. 使用 netty-websocket-spring-boot-starter快速构建基于Netty的Websocket服务
. 介绍 netty-websocket-spring-boot-starter 相关API


https://blog.csdn.net/weixin_33701564/article/details/91762103[高并发测试Websocket脚本]

. 基于Python实现的并发测试脚本

https://blog.csdn.net/vicky_lov/article/details/86569981[基于JMeter-WebsocketSampler的性能测试]

. 介绍了Websocket性能测试场景
.. 大量连接的创建和关闭——不断模拟大量用户对Websocket连接的创建、关闭过程
.. 长时间保持大量连接——创建大量连接、保持连接较长实践
.. 大量推送消息——可以少量连接较长时间保持，不断触发消息推送
. 如何使用jmeter-websocketSampler进行性能测试

行业方案：

https://www.infoq.cn/article/3WpGbP2NEvgjzoWZbLHx[爱奇艺：构建通用 WebSocket 推送网关的设计与实践]

. 介绍了爱奇艺号WebSocket使用现状
. 分析了通用长连接网关在爱奇艺的实现必要性，介绍了设计方案与技术选型分析
. 介绍了长连接网关系统架构、会话管理、监控与报警以及性能压测
. 介绍了长连接网关实现后在爱奇艺业务场景应用的案例及效果






